version: '3'

services:
  api:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: fastapi-application
    environment:
      PORT: 8008
    volumes:
      - ./app:/app
      - ./data:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008
    ports:
      - '8008:8008'
    restart: "no"
